### ISSUE TITLE
TypeError: isGit is not a function

### ISSUE THREAD

**Issue by gluons** [JPeer264/node-is-git-repository#1]
I've used `isGit` as [your documentation](https://github.com/JPeer264/node-is-git-repository/blob/11d0930ecd75a15bf01ea8232d64047d8342f99b/README.md) but I get error.

**My code:**
```javascript
const isGit = require('is-git-repository');

isGit();
```

**Error output:**
```
/home/illuminator/my-projects/generator-gluons/try.js:3
isGit();
^

TypeError: isGit is not a function
    at Object.<anonymous> (/home/illuminator/my-projects/generator-gluons/try.js:3:1)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:390:7)
    at startup (bootstrap_node.js:150:9)
    at bootstrap_node.js:505:3
```

**Just a screenshot:**

![selection_001](https://cloud.githubusercontent.com/assets/4688092/25774182/df6fdb00-32b4-11e7-9749-541d422c49c1.png)

---

The problem is Babel 6 new behavior (babel/babel#2212). It should be solved by [`babel-plugin-add-module-exports`](https://github.com/59naga/babel-plugin-add-module-exports).

**Comment by JPeer264** [comment]
Thanks for your issue, I will check it ASAP

**Comment by JPeer264** [comment]
@gluons which version of Node do you use?

**Comment by gluons** [comment]
@JPeer264 `v6.10.3`

**Comment by JPeer264** [comment]
Thanks for your hint. Please update to v`1.1.1`

**Comment by gluons** [comment]
Got it. Thank you very much for very fast response. 🙂
